### ISSUE TITLE
Version Status가 P로 등록되었으면 하는 요청에 아이센트릭 답변 

### ISSUE THREAD

**Issue by kimkyuseok** [kimkyuseok/study_git#29]
요청 : Version Status가 P로 등록되었으면 하는데, 이것도 혹시 바꿀 수 있는 방법이 있을까요?

답변 : 컨피그에 있는 csi-tk-io-manager.yml 파일 의 uploaded_version_status_shot_code: "wip" 부분을 P의 쑛코드로 수정하시면 됩니다.

T:\inhouse\pub\shotgrid_auth\VFX_CONFIG_X\env\includes\settings\csi-tk-io-manager.yml  파일이 있음 

``` yml
# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

################################################################################

includes:
- ../app_locations.yml

################################################################################


################################################################################


# ---- Stand alone

settings.csi-tk-io-manager.standalone:
  entities:
  - caption: Projects
    entity_type: Project
    filters: []
    hierarchy: [name]
  template_scan_work_area: io_manager_scan_work_area
  deadline_webservice_ip: "10.10.10.23"
  deadline_webservice_port: 8081
  deadline_pool: "io"
  deadline_sec_pool: "io"
  deadline_nuke_version: "13.0"
  deadline_nuke_actual_path: "C:/Program Files/Nuke13.1v2/Nuke13.1.exe"
  deadline_python_version: "3.7"
  deadline_sg_module_path: "T:/inhouse/pub/shotgrid/apps/tk-io-manager/site-packages/py3"
  uploaded_version_status_short_code: "p"
  location: "@apps.csi-tk-io-manager.location"

################################################################################
```
```
  uploaded_version_status_short_code: "wip"
  uploaded_version_status_short_code: "p"
```
여기를 수정함
